### ISSUE TITLE
Make it possible to create two disks and attach them to the same VM at the same time

### ISSUE THREAD

**Issue by remilapeyre** [Cloud-Temple/terraform-provider-cloudtemple#10]

**Comment by pbesret** [comment]
For information I spent a lot of time working on the provider to implement a feature allowing to declare virtual disks directly in the cloudtemple_compute_virtual_machine resource.

In the end, I won't go through with it. I clearly see that even if some other providers do it (vsphere for example), it goes against the way Terraform works. You have to recreate a logic that is already there, preventing us from using very useful features.

Knowing that we can do without it, I prefer not to release something that will not be stable and take the risk of causing data loss.

I hope that a sub-resource system will be available in a future version of Terraform, in which case we'll have to revisit the question, but for the time being I'd rather move on to another topic.
