### ISSUE TITLE
Support for NVMe Controllers

### ISSUE THREAD

**Issue by JoshDelPaso** [Cloud-Temple/terraform-provider-cloudtemple#123]
Hello,

I've encountered an issue with certain templates on Shiva. Specifically, these templates utilize NVMe controllers. I opted for NVMe due to the superior IOPS performance when compared to lsilogic and pvscsi.

I'm curious to know if there are plans to make this option available in the future.

Thanks,

Cheers,

**Comment by pbesret** [comment]
Hello, this feature will be released soon on Compute API. Thus, I will be able to start working on it in the next weeks.
