### ISSUE TITLE
Error SPP policy assignment following terraform with parallelism at 5 VMs

### ISSUE THREAD

**Issue by ThomasAgs** [Cloud-Temple/terraform-provider-cloudtemple#125]
Hello, 

The customer is doing parralelism with 5 VMs to deploy his environment, he has done 39 VMs but there are a few that have not had their SPP policy assigned due to SPP error 500, Platform told me that it's probably the SPP that crashes because of too much use, I told the customer to set a random tempo for policy assignment but since then he has another error which is "Could not find virtual disk 1b80c9bb-701e-440b-a9b8-32dc1e54103b in compute/SPP".
Could not find virtual disk "UUID" in compute/SPP." No problem on the SPP server, maybe a problem on the SHIVA provider side.

Thanks.

**Comment by pbesret** [comment]
Hello,

Your problem should be fixed be release v0.12.4-rc.2 of the provider.

Please let us know if you still have troubles using the provider.

Best regards,
