### ISSUE TITLE
Find how to implement deleting a running VM

### ISSUE THREAD

**Issue by remilapeyre** [Cloud-Temple/terraform-provider-cloudtemple#13]

**Comment by aureldsn** [comment]
After internal discussions, the best user experience is to integrate the shutdown of the virtual machine before deleting it like other providers ([aws](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ec2_instance.go#L2795), [vsphere](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/resource_vsphere_virtual_machine.go#L873-L882))

To avoid accidental destruction, we need to define the `prevent_destroy` variable on critical resources.
