### ISSUE TITLE
Feature request : allow observability management with terraform provider

### ISSUE THREAD

**Issue by julienmorot-ct** [Cloud-Temple/terraform-provider-cloudtemple#140]
Hello,

Shiva's provider currently allow to manage compute and backup resources.

I'd like to be able to manage observability resources the same way I currently manage compute resources : 

- Create monitored hosts
- Attach monitoring services
- Manage scheduled downtimes
- Sync appliances when changes are detected

This feature will allow to cover a wider range of virtual machine lifecycle throught a unified API.

Thanks

**Comment by pbesret** [comment]
Hello, thanks for your message.

Your feature request will be reviewed in the next few days then we'll come back to you.

Regards,
Paul.
