### ISSUE TITLE
cloudtemple_compute_virtual_machine: Update guest_operating_system_moref value

### ISSUE THREAD

**Issue by aureldsn** [Cloud-Temple/terraform-provider-cloudtemple#24]
Currently, we cannot update the guest os value on a virtual machine without destroying it.

An API call is available to update this value: 

PATCH `/v1/vcenters/virtual_machines/{id}/guest`

```
{"guestOperatingSystemMoref":"debian10_64Guest"}
```

Moreover, there is a conflict between `guest_operating_system_moref` and `clone_virtual_machine_id`/`content_library_item_id`, this must be removed and changed by after the virtual machine creation from content library or clone, request an update of the guest os value (PATCH `/v1/vcenters/virtual_machines/{id}/guest`).

### Terraform Version

```
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/cloud-temple/cloudtemple v0.4.2
```

### Affected Resource(s)

- cloudtemple_compute_virtual_machine

### Terraform Configuration Files

```hcl
data "cloudtemple_compute_virtual_datacenter" "lab" {
  name = "DC-ITX7"
}

data "cloudtemple_compute_host_cluster" "lab" {
  name = "clu003-ucs02_LAB01"
}

data "cloudtemple_compute_datastore_cluster" "lab" {
  name = "sdrs003-LIVE_LAB01"
}

data "cloudtemple_compute_network" "lab" {
  name = "ISC-LAB-DC-ITX7"
}

resource "cloudtemple_compute_virtual_machine" "ads-test-002" {
  name = "ads-test-002"

  memory                 = 1 * 1024 * 1024 * 1024
  cpu                    = 1
  num_cores_per_socket   = 1
  cpu_hot_add_enabled    = true
  cpu_hot_remove_enabled = true
  memory_hot_add_enabled = true

  virtual_datacenter_id        = data.cloudtemple_compute_virtual_datacenter.lab.id
  host_cluster_id              = data.cloudtemple_compute_host_cluster.lab.id
  datastore_cluster_id         = data.cloudtemple_compute_datastore_cluster.lab.id
  guest_operating_system_moref = "debian10_64Guest"

  power_state = "off"

  tags = {
    created_by = "Terraform",
    env        = "lab",
  }

  lifecycle {
    ignore_changes = [virtual_datacenter_id]
  }
}
```

### Expected Behavior

When I change the value of `guest_operating_system_moref`, terraform should only update this value without any trouble.

### Actual Behavior

When I change the value of `guest_operating_system_moref`, terraform wants to rebuild the virtual machine or deny this change if the virtual machine is built from a content library or a clone.

### Steps to Reproduce

1. Create a virtual machine with a guest os value set to `debian10_64Guest`
2. Update the guest os value to `debian11_64Guest`

or 

1. Create a virtual machine from content library with a guest os value set to `debian11_64Guest`

**Comment by pbesret** [comment]
Fixed with PR https://github.com/Cloud-Temple/terraform-provider-cloudtemple/pull/31.
I close the issue.
