### ISSUE TITLE
Windows Guest OS Customization

### ISSUE THREAD

**Issue by roct37** [Cloud-Temple/terraform-provider-cloudtemple#75]
**Is your feature request related to a problem? Please describe.**
There is actually no mechanism allowing to customize a Windows guest when deploying a VM on shiva. This means, the virtual machine needs to be manually configured for basic options like network or hostname.

**Describe the solution you'd like**
I'd like to be able to customize my Windows like its possible with the vmware terraform provider using customize block.

**Describe alternatives you've considered**
Nothing at the moment as provisionner are not recommended by terraform and would also recquire development

**Comment by pbesret** [comment]
Hello,

Have you tried using our cloud-init feature with an Windows Server image that's Cloudbase-init ready ?

**Comment by pbesret** [comment]
Hello,

The version release today (v0.12.0) contains a feature allowing you to customize your Guest OS.
NB : Use the specific `windows_config` parameter block inside the `customize` block in your case. 

Thanks,
Paul.
