### ISSUE TITLE
Following the last release 0.10.0-rc.2 - Import disk issue with controller

### ISSUE THREAD

**Issue by JoshDelPaso** [Cloud-Temple/terraform-provider-cloudtemple#98]
Hello,

Following the last release 0.10.0-rc.2, I tested to import a disk, but I've gotten an issue when I put the controller in my disk ressource (see below) :

<img width="362" alt="Screenshot 2023-11-09 105711" src="https://github.com/Cloud-Temple/terraform-provider-cloudtemple/assets/54177066/5380b57d-9c05-4e19-a759-5bf6782e7914">

at the next "terraform apply" :

<img width="642" alt="Screenshot 2023-11-09 105642" src="https://github.com/Cloud-Temple/terraform-provider-cloudtemple/assets/54177066/c281665c-acf7-4058-b4e4-af76e76de8f1">

However, when I remove from my state the disk, and reimport it without the "controller_id", the next apply works pretty well : 
<img width="607" alt="Screenshot 2023-11-09 105901" src="https://github.com/Cloud-Temple/terraform-provider-cloudtemple/assets/54177066/c723ad44-2edf-45b1-81ea-66f5f2a0465f">
I think this issue is linked to the #97 

Thanks,

Cheerio,

**Comment by pbesret** [comment]
Hello, the problem is replicated on our side.
Will try a fix today and get back to you soon.
